;;; ematrix-theme.el --- Refined graphite theme for Emacs  -*- lexical-binding: t; -*-

;; Copyright (C) 2024-2026 Zi Liang

;; Author: Zi Liang <2273067585@qq.com>
;; Version: 0.2.0
;; Package-Requires: ((emacs "27.1"))
;; Keywords: faces, theme
;; URL: https://github.com/liangzid/ematrix

;;; Commentary:
;;
;; EMatrix is a restrained dark theme built around a neutral graphite canvas,
;; soft text, and a compact set of semantic accents.  It is designed for long
;; research and programming sessions, including mixed Latin and CJK text.

;;; Code:

(deftheme ematrix
  "A restrained graphite theme with precise semantic accents.")

;; REVIEW: These three layers define the visual hierarchy.  Most text stays on
;; `bg-main'; transient UI uses `bg-raised'; selection uses `bg-active'.
(let* ((bg-main       "#111318")
       (bg-surface    "#161920")
       (bg-raised     "#1C2029")
       (bg-active     "#252B38")
       (bg-selection  "#2D3749")
       (bg-highlight  "#1A1E27")
       (fg-main       "#D6D9E0")
       (fg-strong     "#ECEEF2")
       (fg-muted      "#9AA2B1")
       (fg-subtle     "#697282")
       (fg-faint      "#4C5461")
       (red           "#E27878")
       (red-bright    "#F08A8A")
       (orange        "#D5A06B")
       (yellow        "#D8BE7B")
       (green         "#8FBE83")
       (green-bright  "#A6CF98")
       (teal          "#77BEB7")
       (cyan          "#79B8D1")
       (blue          "#82A7E8")
       (purple        "#B49ADD")
       (magenta       "#CA8FAF")
       (black         "#0B0D11")
       (diff-add-bg   "#17261D")
       (diff-del-bg   "#2A191C")
       (diff-change-bg "#292419"))

  (custom-theme-set-faces
   'ematrix

   ;; Foundation
   `(default ((t (:background ,bg-main :foreground ,fg-main))))
   `(fixed-pitch ((t (:foreground ,fg-main))))
   `(fixed-pitch-serif ((t (:foreground ,fg-main))))
   `(variable-pitch ((t (:foreground ,fg-main))))
   `(cursor ((t (:background ,fg-strong))))
   `(fringe ((t (:background ,bg-main :foreground ,fg-faint))))
   `(vertical-border ((t (:foreground ,bg-raised))))
   `(window-divider ((t (:foreground ,bg-raised))))
   `(window-divider-first-pixel ((t (:foreground ,bg-main))))
   `(window-divider-last-pixel ((t (:foreground ,bg-main))))
   `(region ((t (:background ,bg-selection :extend t))))
   `(highlight ((t (:background ,bg-active))))
   `(secondary-selection ((t (:background ,bg-active))))
   `(hl-line ((t (:background ,bg-highlight :extend t))))
   `(shadow ((t (:foreground ,fg-subtle))))
   `(success ((t (:foreground ,green :weight semi-bold))))
   `(warning ((t (:foreground ,yellow :weight semi-bold))))
   `(error ((t (:foreground ,red :weight semi-bold))))
   `(link ((t (:foreground ,blue :underline t))))
   `(link-visited ((t (:foreground ,purple :underline t))))
   `(button ((t (:foreground ,blue :underline t))))
   `(escape-glyph ((t (:foreground ,orange))))
   `(homoglyph ((t (:foreground ,orange))))
   `(trailing-whitespace ((t (:background ,red))))
   `(whitespace-tab ((t (:foreground ,fg-faint))))
   `(whitespace-space ((t (:foreground ,fg-faint))))
   `(whitespace-newline ((t (:foreground ,fg-faint))))
   `(fill-column-indicator ((t (:foreground ,bg-active))))

   ;; Line numbers and structural guides
   `(line-number ((t (:background ,bg-main :foreground ,fg-faint))))
   `(line-number-current-line ((t (:background ,bg-main :foreground ,fg-strong :weight semi-bold))))
   `(line-number-major-tick ((t (:foreground ,blue :weight bold))))
   `(line-number-minor-tick ((t (:foreground ,fg-muted))))
   `(highlight-indentation-face ((t (:background ,bg-raised))))
   `(highlight-indentation-current-column-face ((t (:background ,bg-active))))
   `(indent-bars-face ((t (:foreground ,bg-active))))
   `(indent-bars-current-face ((t (:foreground ,fg-subtle))))

   ;; Typography and syntax
   `(font-lock-bracket-face ((t (:foreground ,fg-muted))))
   `(font-lock-builtin-face ((t (:foreground ,cyan))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,fg-subtle))))
   `(font-lock-comment-face ((t (:foreground ,fg-muted :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,orange))))
   `(font-lock-delimiter-face ((t (:foreground ,fg-muted))))
   `(font-lock-doc-face ((t (:foreground ,fg-muted))))
   `(font-lock-doc-markup-face ((t (:foreground ,teal))))
   `(font-lock-escape-face ((t (:foreground ,yellow))))
   `(font-lock-function-call-face ((t (:foreground ,cyan))))
   `(font-lock-function-name-face ((t (:foreground ,cyan :weight medium))))
   `(font-lock-keyword-face ((t (:foreground ,purple :weight semi-bold))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,fg-muted))))
   `(font-lock-negation-char-face ((t (:foreground ,red))))
   `(font-lock-number-face ((t (:foreground ,orange))))
   `(font-lock-operator-face ((t (:foreground ,fg-muted))))
   `(font-lock-preprocessor-face ((t (:foreground ,magenta))))
   `(font-lock-property-name-face ((t (:foreground ,teal))))
   `(font-lock-property-use-face ((t (:foreground ,teal))))
   `(font-lock-punctuation-face ((t (:foreground ,fg-muted))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,yellow))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,purple))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,yellow))))
   `(font-lock-variable-name-face ((t (:foreground ,fg-main))))
   `(font-lock-variable-use-face ((t (:foreground ,fg-main))))
   `(font-lock-warning-face ((t (:foreground ,red-bright :weight semi-bold))))

   ;; Parentheses and search
   `(show-paren-match ((t (:background ,bg-selection :foreground ,fg-strong :weight bold))))
   `(show-paren-match-expression ((t (:background ,bg-active))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,black :weight bold))))
   `(isearch ((t (:background ,yellow :foreground ,black :weight bold))))
   `(isearch-fail ((t (:background ,red :foreground ,black :weight bold))))
   `(lazy-highlight ((t (:background ,bg-selection :foreground ,fg-strong))))
   `(match ((t (:background ,bg-selection :foreground ,yellow :weight semi-bold))))
   `(query-replace ((t (:inherit isearch))))

   ;; Modeline, header line, tabs, and minibuffer
   `(mode-line ((t (:background ,bg-raised :foreground ,fg-main :box nil))))
   `(mode-line-active ((t (:inherit mode-line))))
   `(mode-line-inactive ((t (:background ,bg-main :foreground ,fg-subtle :box nil))))
   `(mode-line-buffer-id ((t (:foreground ,fg-strong :weight semi-bold))))
   `(mode-line-emphasis ((t (:foreground ,blue :weight semi-bold))))
   `(mode-line-highlight ((t (:background ,bg-active))))
   `(header-line ((t (:background ,bg-surface :foreground ,fg-muted :box nil))))
   `(header-line-highlight ((t (:background ,bg-active :foreground ,fg-main))))
   `(minibuffer-prompt ((t (:foreground ,blue :weight semi-bold))))
   `(tab-bar ((t (:background ,bg-main :foreground ,fg-muted :box nil))))
   `(tab-bar-tab ((t (:background ,bg-raised :foreground ,fg-strong :box nil :weight semi-bold))))
   `(tab-bar-tab-inactive ((t (:background ,bg-main :foreground ,fg-subtle :box nil))))
   `(tab-line ((t (:background ,bg-main :foreground ,fg-muted :box nil))))
   `(tab-line-tab-current ((t (:background ,bg-raised :foreground ,fg-strong :box nil :weight semi-bold))))
   `(tab-line-tab-inactive ((t (:background ,bg-main :foreground ,fg-subtle :box nil))))
   `(tab-line-highlight ((t (:background ,bg-active :foreground ,fg-main))))

   ;; Generic widgets and popup UI
   `(tooltip ((t (:background ,bg-raised :foreground ,fg-main))))
   `(widget-field ((t (:background ,bg-raised :foreground ,fg-main))))
   `(widget-button ((t (:foreground ,blue :weight semi-bold))))
   `(custom-button ((t (:background ,bg-raised :foreground ,fg-main :box (:line-width 1 :color ,fg-subtle)))))
   `(custom-button-mouse ((t (:background ,bg-active :foreground ,fg-strong))))
   `(custom-button-pressed ((t (:background ,blue :foreground ,black))))
   `(custom-changed ((t (:foreground ,yellow))))
   `(custom-modified ((t (:foreground ,orange))))
   `(custom-state ((t (:foreground ,green))))
   `(custom-variable-tag ((t (:foreground ,purple :weight semi-bold))))

   ;; Completion framework
   `(completions-annotations ((t (:foreground ,fg-muted))))
   `(completions-common-part ((t (:foreground ,blue :weight semi-bold))))
   `(completions-first-difference ((t (:foreground ,fg-strong))))
   `(company-tooltip ((t (:background ,bg-raised :foreground ,fg-main))))
   `(company-tooltip-selection ((t (:background ,bg-selection :foreground ,fg-strong))))
   `(company-tooltip-common ((t (:foreground ,blue :weight semi-bold))))
   `(company-tooltip-common-selection ((t (:foreground ,cyan :weight semi-bold))))
   `(company-tooltip-annotation ((t (:foreground ,fg-muted))))
   `(company-tooltip-annotation-selection ((t (:foreground ,fg-main))))
   `(company-tooltip-search ((t (:foreground ,yellow :weight bold))))
   `(company-tooltip-search-selection ((t (:foreground ,yellow :weight bold))))
   `(company-scrollbar-fg ((t (:background ,fg-subtle))))
   `(company-scrollbar-bg ((t (:background ,bg-surface))))
   `(company-preview ((t (:background ,bg-active :foreground ,fg-muted))))
   `(company-preview-common ((t (:foreground ,blue))))
   `(ivy-current-match ((t (:background ,bg-selection :foreground ,fg-strong :weight semi-bold))))
   `(ivy-minibuffer-match-face-1 ((t (:foreground ,fg-muted))))
   `(ivy-minibuffer-match-face-2 ((t (:foreground ,blue :weight semi-bold))))
   `(ivy-minibuffer-match-face-3 ((t (:foreground ,teal :weight semi-bold))))
   `(ivy-minibuffer-match-face-4 ((t (:foreground ,purple :weight semi-bold))))
   `(ivy-posframe ((t (:background ,bg-raised :foreground ,fg-main))))
   `(ivy-posframe-border ((t (:background ,fg-subtle))))
   `(ivy-posframe-cursor ((t (:background ,fg-strong))))
   `(vertico-current ((t (:background ,bg-selection :foreground ,fg-strong :weight semi-bold))))
   `(orderless-match-face-0 ((t (:foreground ,blue :weight semi-bold))))
   `(orderless-match-face-1 ((t (:foreground ,teal :weight semi-bold))))
   `(orderless-match-face-2 ((t (:foreground ,purple :weight semi-bold))))
   `(orderless-match-face-3 ((t (:foreground ,orange :weight semi-bold))))
   `(marginalia-key ((t (:foreground ,teal))))
   `(marginalia-file-name ((t (:foreground ,fg-main))))
   `(marginalia-file-size ((t (:foreground ,fg-subtle))))
   `(marginalia-mode ((t (:foreground ,purple))))
   `(marginalia-date ((t (:foreground ,fg-muted))))
   `(marginalia-documentation ((t (:foreground ,fg-muted :slant italic))))

   ;; Which-key
   `(which-key-key-face ((t (:foreground ,blue :weight semi-bold))))
   `(which-key-command-description-face ((t (:foreground ,fg-main))))
   `(which-key-group-description-face ((t (:foreground ,purple))))
   `(which-key-local-map-description-face ((t (:foreground ,teal))))
   `(which-key-note-face ((t (:foreground ,fg-muted))))
   `(which-key-separator-face ((t (:foreground ,fg-faint))))
   `(which-key-special-key-face ((t (:foreground ,yellow))))

   ;; Dired and file navigation
   `(dired-directory ((t (:foreground ,blue :weight semi-bold))))
   `(dired-symlink ((t (:foreground ,teal))))
   `(dired-mark ((t (:foreground ,yellow :weight bold))))
   `(dired-marked ((t (:background ,bg-active :foreground ,yellow :weight semi-bold))))
   `(dired-flagged ((t (:foreground ,red :weight semi-bold))))
   `(dired-header ((t (:foreground ,purple :weight semi-bold))))
   `(dired-ignored ((t (:foreground ,fg-faint))))
   `(dired-broken-symlink ((t (:background ,red :foreground ,black))))
   `(dired-special ((t (:foreground ,orange))))
   `(dired-warning ((t (:foreground ,red))))
   `(neo-root-dir-face ((t (:foreground ,fg-strong :weight bold))))
   `(neo-dir-link-face ((t (:foreground ,blue))))
   `(neo-file-link-face ((t (:foreground ,fg-main))))
   `(neo-expand-btn-face ((t (:foreground ,fg-subtle))))

   ;; Org and agenda
   `(org-document-title ((t (:foreground ,fg-strong :weight bold :height 1.45))))
   `(org-document-info ((t (:foreground ,fg-muted))))
   `(org-document-info-keyword ((t (:foreground ,fg-subtle))))
   `(org-level-1 ((t (:foreground ,blue :weight bold :height 1.28))))
   `(org-level-2 ((t (:foreground ,purple :weight bold :height 1.18))))
   `(org-level-3 ((t (:foreground ,teal :weight semi-bold :height 1.10))))
   `(org-level-4 ((t (:foreground ,yellow :weight semi-bold))))
   `(org-level-5 ((t (:foreground ,cyan :weight semi-bold))))
   `(org-level-6 ((t (:foreground ,orange))))
   `(org-level-7 ((t (:foreground ,green))))
   `(org-level-8 ((t (:foreground ,magenta))))
   `(org-block ((t (:background ,bg-surface :foreground ,fg-main :extend t))))
   `(org-block-begin-line ((t (:background ,bg-raised :foreground ,fg-subtle :extend t))))
   `(org-block-end-line ((t (:background ,bg-raised :foreground ,fg-faint :extend t))))
   `(org-code ((t (:foreground ,green))))
   `(org-verbatim ((t (:foreground ,yellow))))
   `(org-quote ((t (:background ,bg-surface :foreground ,fg-muted :slant italic :extend t))))
   `(org-meta-line ((t (:foreground ,fg-subtle))))
   `(org-special-keyword ((t (:foreground ,purple))))
   `(org-drawer ((t (:foreground ,fg-subtle))))
   `(org-property-value ((t (:foreground ,fg-muted))))
   `(org-link ((t (:foreground ,blue :underline t))))
   `(org-date ((t (:foreground ,cyan))))
   `(org-tag ((t (:foreground ,purple :weight normal))))
   `(org-todo ((t (:foreground ,orange :weight bold))))
   `(org-done ((t (:foreground ,green :weight semi-bold))))
   `(org-headline-done ((t (:foreground ,fg-subtle :strike-through t))))
   `(org-checkbox ((t (:foreground ,teal :weight semi-bold))))
   `(org-list-dt ((t (:foreground ,teal :weight semi-bold))))
   `(org-table ((t (:foreground ,cyan))))
   `(org-formula ((t (:foreground ,orange))))
   `(org-footnote ((t (:foreground ,purple))))
   `(org-ellipsis ((t (:foreground ,fg-subtle))))
   `(org-hide ((t (:foreground ,bg-main))))
   `(org-sexp-date ((t (:foreground ,cyan))))
   `(org-archived ((t (:foreground ,fg-faint))))
   `(org-priority ((t (:foreground ,red :weight semi-bold))))
   `(org-scheduled ((t (:foreground ,green))))
   `(org-scheduled-today ((t (:foreground ,teal :weight semi-bold))))
   `(org-scheduled-previously ((t (:foreground ,red))))
   `(org-upcoming-deadline ((t (:foreground ,orange))))
   `(org-warning ((t (:foreground ,red :weight semi-bold))))
   `(org-agenda-structure ((t (:foreground ,blue :weight bold))))
   `(org-agenda-date ((t (:foreground ,cyan :weight semi-bold))))
   `(org-agenda-date-today ((t (:foreground ,fg-strong :weight bold :height 1.12))))
   `(org-agenda-date-weekend ((t (:foreground ,purple))))
   `(org-agenda-current-time ((t (:foreground ,orange :weight semi-bold))))
   `(org-agenda-done ((t (:foreground ,fg-subtle :strike-through t))))
   `(org-agenda-dimmed-todo-face ((t (:foreground ,fg-faint))))
   `(org-time-grid ((t (:foreground ,fg-faint))))
   `(org-habit-clear-face ((t (:background ,bg-active))))
   `(org-habit-clear-future-face ((t (:background ,bg-raised))))
   `(org-habit-ready-face ((t (:background ,green :foreground ,black))))
   `(org-habit-ready-future-face ((t (:background ,diff-add-bg :foreground ,green))))
   `(org-habit-alert-face ((t (:background ,yellow :foreground ,black))))
   `(org-habit-alert-future-face ((t (:background ,diff-change-bg :foreground ,yellow))))
   `(org-habit-overdue-face ((t (:background ,red :foreground ,black))))
   `(org-habit-overdue-future-face ((t (:background ,diff-del-bg :foreground ,red))))
   `(org-visual-indent-pipe-face ((t (:foreground ,bg-active))))
   `(org-visual-indent-blank-pipe-face ((t (:foreground ,bg-raised))))

   ;; Markdown
   `(markdown-header-face-1 ((t (:foreground ,blue :weight bold :height 1.28))))
   `(markdown-header-face-2 ((t (:foreground ,purple :weight bold :height 1.18))))
   `(markdown-header-face-3 ((t (:foreground ,teal :weight semi-bold :height 1.10))))
   `(markdown-header-face-4 ((t (:foreground ,yellow :weight semi-bold))))
   `(markdown-header-face-5 ((t (:foreground ,cyan))))
   `(markdown-header-face-6 ((t (:foreground ,orange))))
   `(markdown-header-delimiter-face ((t (:foreground ,fg-faint))))
   `(markdown-link-face ((t (:foreground ,blue :underline t))))
   `(markdown-url-face ((t (:foreground ,fg-subtle))))
   `(markdown-inline-code-face ((t (:background ,bg-surface :foreground ,green))))
   `(markdown-code-face ((t (:background ,bg-surface :foreground ,fg-main :extend t))))
   `(markdown-pre-face ((t (:background ,bg-surface :foreground ,fg-main :extend t))))
   `(markdown-blockquote-face ((t (:foreground ,fg-muted :slant italic))))
   `(markdown-italic-face ((t (:foreground ,fg-main :slant italic))))
   `(markdown-bold-face ((t (:foreground ,fg-strong :weight bold))))
   `(markdown-markup-face ((t (:foreground ,fg-subtle))))
   `(markdown-list-face ((t (:foreground ,purple))))
   `(markdown-metadata-key-face ((t (:foreground ,teal))))
   `(markdown-metadata-value-face ((t (:foreground ,fg-muted))))

   ;; LaTeX and AUCTeX
   `(font-latex-bold-face ((t (:foreground ,fg-strong :weight bold))))
   `(font-latex-italic-face ((t (:foreground ,fg-main :slant italic))))
   `(font-latex-math-face ((t (:foreground ,teal))))
   `(font-latex-script-char-face ((t (:foreground ,orange))))
   `(font-latex-sectioning-0-face ((t (:foreground ,blue :weight bold :height 1.35))))
   `(font-latex-sectioning-1-face ((t (:foreground ,blue :weight bold :height 1.28))))
   `(font-latex-sectioning-2-face ((t (:foreground ,purple :weight bold :height 1.20))))
   `(font-latex-sectioning-3-face ((t (:foreground ,teal :weight semi-bold :height 1.14))))
   `(font-latex-sectioning-4-face ((t (:foreground ,yellow :weight semi-bold :height 1.08))))
   `(font-latex-sectioning-5-face ((t (:foreground ,cyan :weight semi-bold))))
   `(font-latex-sedate-face ((t (:foreground ,fg-muted))))
   `(font-latex-slide-title-face ((t (:foreground ,blue :weight bold :height 1.30))))
   `(font-latex-string-face ((t (:foreground ,green))))
   `(font-latex-subscript-face ((t (:foreground ,orange :height 0.90))))
   `(font-latex-superscript-face ((t (:foreground ,orange :height 0.90))))
   `(font-latex-verbatim-face ((t (:background ,bg-surface :foreground ,green))))
   `(font-latex-warning-face ((t (:foreground ,red :weight semi-bold))))

   ;; Diff, Ediff, and version control
   `(diff-added ((t (:background ,diff-add-bg :foreground ,green-bright :extend t))))
   `(diff-removed ((t (:background ,diff-del-bg :foreground ,red-bright :extend t))))
   `(diff-changed ((t (:background ,diff-change-bg :foreground ,yellow :extend t))))
   `(diff-refine-added ((t (:background "#28402F" :foreground ,fg-strong))))
   `(diff-refine-removed ((t (:background "#48262B" :foreground ,fg-strong))))
   `(diff-header ((t (:background ,bg-surface :foreground ,fg-muted))))
   `(diff-file-header ((t (:background ,bg-raised :foreground ,fg-strong :weight semi-bold))))
   `(diff-hunk-header ((t (:background ,bg-active :foreground ,cyan))))
   `(diff-function ((t (:foreground ,purple))))
   `(diff-context ((t (:foreground ,fg-muted))))
   `(ediff-current-diff-A ((t (:background ,diff-del-bg :foreground ,red-bright))))
   `(ediff-current-diff-B ((t (:background ,diff-add-bg :foreground ,green-bright))))
   `(ediff-current-diff-C ((t (:background ,diff-change-bg :foreground ,yellow))))
   `(ediff-fine-diff-A ((t (:background "#48262B" :foreground ,fg-strong))))
   `(ediff-fine-diff-B ((t (:background "#28402F" :foreground ,fg-strong))))
   `(ediff-fine-diff-C ((t (:background "#494126" :foreground ,fg-strong))))
   `(magit-section-heading ((t (:foreground ,blue :weight bold))))
   `(magit-section-highlight ((t (:background ,bg-highlight))))
   `(magit-branch-current ((t (:foreground ,green :weight semi-bold :box (:line-width 1 :color ,green)))))
   `(magit-branch-local ((t (:foreground ,blue))))
   `(magit-branch-remote ((t (:foreground ,teal))))
   `(magit-branch-upstream ((t (:foreground ,purple))))
   `(magit-tag ((t (:foreground ,yellow :weight semi-bold))))
   `(magit-hash ((t (:foreground ,fg-subtle))))
   `(magit-log-author ((t (:foreground ,orange))))
   `(magit-log-date ((t (:foreground ,fg-subtle))))
   `(magit-log-graph ((t (:foreground ,fg-faint))))
   `(magit-diff-file-heading ((t (:foreground ,fg-strong :weight semi-bold))))
   `(magit-diff-file-heading-highlight ((t (:background ,bg-active :foreground ,fg-strong))))
   `(magit-diff-hunk-heading ((t (:background ,bg-raised :foreground ,fg-muted))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,bg-active :foreground ,cyan))))
   `(magit-diff-added ((t (:background ,diff-add-bg :foreground ,green-bright))))
   `(magit-diff-removed ((t (:background ,diff-del-bg :foreground ,red-bright))))
   `(magit-diff-context-highlight ((t (:background ,bg-highlight :foreground ,fg-muted))))
   `(magit-diffstat-added ((t (:foreground ,green))))
   `(magit-diffstat-removed ((t (:foreground ,red))))
   `(magit-process-ok ((t (:foreground ,green :weight semi-bold))))
   `(magit-process-ng ((t (:foreground ,red :weight semi-bold))))
   `(magit-dimmed ((t (:foreground ,fg-faint))))
   `(git-gutter:added ((t (:foreground ,green :weight bold))))
   `(git-gutter:deleted ((t (:foreground ,red :weight bold))))
   `(git-gutter:modified ((t (:foreground ,yellow :weight bold))))

   ;; Diagnostics, compilation, and navigation
   `(flymake-error ((t (:underline (:style wave :color ,red)))))
   `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flymake-note ((t (:underline (:style wave :color ,blue)))))
   `(flycheck-error ((t (:underline (:style wave :color ,red)))))
   `(flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flycheck-info ((t (:underline (:style wave :color ,blue)))))
   `(compilation-error ((t (:foreground ,red))))
   `(compilation-warning ((t (:foreground ,yellow))))
   `(compilation-info ((t (:foreground ,green))))
   `(compilation-line-number ((t (:foreground ,blue))))
   `(compilation-column-number ((t (:foreground ,cyan))))
   `(grep-hit-face ((t (:foreground ,green))))
   `(grep-match-face ((t (:background ,bg-selection :foreground ,yellow :weight semi-bold))))
   `(xref-file-header ((t (:foreground ,blue :weight semi-bold))))
   `(xref-line-number ((t (:foreground ,fg-subtle))))
   `(xref-match ((t (:background ,bg-selection :foreground ,yellow :weight semi-bold))))
   `(eglot-highlight-symbol-face ((t (:background ,bg-active))))
   `(citre-peek-header-face ((t (:background ,bg-raised :foreground ,fg-strong))))
   `(citre-peek-symbol-face ((t (:foreground ,yellow :weight semi-bold))))
   `(citre-mark-face ((t (:background ,bg-selection))))

   ;; Doom modeline and modal editing
   `(doom-modeline-bar ((t (:background ,blue))))
   `(doom-modeline-bar-inactive ((t (:background ,bg-active))))
   `(doom-modeline-buffer-file ((t (:foreground ,fg-strong :weight semi-bold))))
   `(doom-modeline-buffer-path ((t (:foreground ,fg-muted))))
   `(doom-modeline-info ((t (:foreground ,blue))))
   `(doom-modeline-warning ((t (:foreground ,yellow))))
   `(doom-modeline-urgent ((t (:foreground ,red))))
   `(doom-modeline-project-dir ((t (:foreground ,purple :weight semi-bold))))
   `(doom-modeline-buffer-major-mode ((t (:foreground ,teal :weight semi-bold))))
   `(winum-face ((t (:foreground ,blue :weight bold))))
   `(evil-ex-lazy-highlight ((t (:background ,bg-selection))))
   `(evil-ex-substitute-matches ((t (:background ,red :foreground ,black))))
   `(evil-ex-substitute-replacement ((t (:background ,green :foreground ,black))))
   `(evil-goggles-default-face ((t (:background ,bg-selection))))

   ;; Rainbow delimiters retain depth without dominating syntax.
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,blue))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,purple))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,teal))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,yellow))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,cyan))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,orange))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,magenta))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,green))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,fg-muted))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,red :weight bold))))
   `(rainbow-delimiters-mismatched-face ((t (:background ,red :foreground ,black :weight bold))))

   ;; Shells and terminals
   `(eshell-prompt ((t (:foreground ,blue :weight bold))))
   `(eshell-ls-directory ((t (:foreground ,blue :weight semi-bold))))
   `(eshell-ls-symlink ((t (:foreground ,teal))))
   `(eshell-ls-executable ((t (:foreground ,green))))
   `(eshell-ls-archive ((t (:foreground ,orange))))
   `(eshell-ls-unreadable ((t (:foreground ,fg-faint))))
   `(term-color-black ((t (:background ,black :foreground ,black))))
   `(term-color-red ((t (:background ,red :foreground ,red))))
   `(term-color-green ((t (:background ,green :foreground ,green))))
   `(term-color-yellow ((t (:background ,yellow :foreground ,yellow))))
   `(term-color-blue ((t (:background ,blue :foreground ,blue))))
   `(term-color-magenta ((t (:background ,purple :foreground ,purple))))
   `(term-color-cyan ((t (:background ,teal :foreground ,teal))))
   `(term-color-white ((t (:background ,fg-main :foreground ,fg-main))))
   `(ansi-color-black ((t (:background ,black :foreground ,black))))
   `(ansi-color-red ((t (:background ,red :foreground ,red))))
   `(ansi-color-green ((t (:background ,green :foreground ,green))))
   `(ansi-color-yellow ((t (:background ,yellow :foreground ,yellow))))
   `(ansi-color-blue ((t (:background ,blue :foreground ,blue))))
   `(ansi-color-magenta ((t (:background ,purple :foreground ,purple))))
   `(ansi-color-cyan ((t (:background ,teal :foreground ,teal))))
   `(ansi-color-white ((t (:background ,fg-main :foreground ,fg-main))))
   `(ansi-color-bright-black ((t (:background ,fg-subtle :foreground ,fg-subtle))))
   `(ansi-color-bright-red ((t (:background ,red-bright :foreground ,red-bright))))
   `(ansi-color-bright-green ((t (:background ,green-bright :foreground ,green-bright))))
   `(ansi-color-bright-yellow ((t (:background ,yellow :foreground ,yellow))))
   `(ansi-color-bright-blue ((t (:background ,blue :foreground ,blue))))
   `(ansi-color-bright-magenta ((t (:background ,magenta :foreground ,magenta))))
   `(ansi-color-bright-cyan ((t (:background ,cyan :foreground ,cyan))))
   `(ansi-color-bright-white ((t (:background ,fg-strong :foreground ,fg-strong))))

   ;; Miscellaneous packages used by this configuration
   `(yas-field-highlight-face ((t (:background ,bg-selection))))
   `(pulse-highlight-start-face ((t (:background ,bg-selection))))
   `(highlight-symbol-face ((t (:background ,bg-active :foreground ,yellow))))
   `(telega-msg-heading ((t (:foreground ,teal :weight semi-bold))))
   `(telega-entity-type-text-link ((t (:foreground ,blue :underline t))))
   `(sly-error-face ((t (:underline (:style wave :color ,red)))))
   `(sly-warning-face ((t (:underline (:style wave :color ,yellow)))))
   `(cider-error-highlight-face ((t (:underline (:style wave :color ,red)))))
   `(cider-warning-highlight-face ((t (:underline (:style wave :color ,yellow))))))

  (custom-theme-set-variables
   'ematrix
   `(ansi-color-names-vector
     [,black ,red ,green ,yellow ,blue ,purple ,teal ,fg-main])
   `(fci-rule-color ,bg-active)
   `(highlight-changes-colors '(,magenta ,purple))
   `(highlight-tail-colors
     '((,bg-raised . 0) (,green . 20) (,teal . 40) (,blue . 60)
       (,purple . 80) (,bg-raised . 100)))
   `(pos-tip-background-color ,bg-raised)
   `(pos-tip-foreground-color ,fg-main)
   `(vc-annotate-background ,bg-main)
   `(vc-annotate-very-old-color ,purple)
   `(vc-annotate-color-map
     '((20 . ,red) (60 . ,orange) (100 . ,yellow) (160 . ,green)
       (220 . ,teal) (280 . ,blue) (340 . ,purple)))
   `(weechat-color-list
     '(unspecified ,black ,bg-raised ,red ,red-bright ,green ,green-bright
       ,yellow ,orange ,blue ,cyan ,purple ,magenta ,teal ,cyan ,fg-main
       ,fg-strong))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'ematrix)
;;; ematrix-theme.el ends here
